 Vagrant.configure("2") do |config|
    config.vm.define "ubuntu1" do |ubuntu1|
        ubuntu1.vm.box = "bento/ubuntu-20.04"
        ubuntu1.vm.network "private_network", ip: "192.168.100.101"
        ubuntu1.vm.network "forwarded_port", guest: 80, host: 8080
        ubuntu1.vm.network "forwarded_port", guest: 443, host: 8443
    end

    config.vm.define "ubuntu2" do |ubuntu2|
        ubuntu2.vm.box = "bento/ubuntu-20.04"
        ubuntu2.vm.network "private_network", ip: "192.168.100.102"
    end
 end