version: "3.9"

services:
  db:
    image: postgres:13.6
    container_name: db-postgres
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
