version: "3.9"

services:
  db:
    image: mysql:8.0.28
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
