version: "3.9"

services:
  db:
    image: postgres:12.10
    container_name: postgresql-db
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - db-data:/var/lib/postgresql/data
      - backup-data:/var/lib/postgresql/backup

volumes:
  db-data:
  backup-data:
